# Generated by Django 4.2 on 2023-04-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="active"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="superuser"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "has_profile",
                    models.BooleanField(default=False, verbose_name="has profile"),
                ),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
            managers=[("objects", users.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="AnimeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Anime",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.animeprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoviesProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MusicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genres", models.TextField(default="")),
                ("artists", models.TextField(default="")),
                ("popularities", models.TextField(default="")),
                ("durations", models.TextField(default="")),
                ("release_dates", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="ReadingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("N", "Non_binary")],
                        max_length=1,
                    ),
                ),
                (
                    "sexual_orientation",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("N", "Non_binary")],
                        max_length=1,
                    ),
                ),
                (
                    "interests",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.interests",
                    ),
                ),
                (
                    "matches",
                    models.ManyToManyField(
                        related_name="matched_user", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "pending",
                    models.ManyToManyField(
                        related_name="pending_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interests",
            name="movies",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.moviesprofile"
            ),
        ),
        migrations.AddField(
            model_name="interests",
            name="music",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.musicprofile"
            ),
        ),
        migrations.AddField(
            model_name="interests",
            name="reading",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.readingprofile"
            ),
        ),
    ]
