# Generated by Django 4.2 on 2023-04-15 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.interests",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="matches",
            field=models.ManyToManyField(
                null=True, related_name="matched_user", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pending",
            field=models.ManyToManyField(
                null=True, related_name="pending_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
