# Generated by Django 4.2 on 2023-04-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_interests_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.interests",
            ),
        ),
    ]
