# Generated by Django 4.2 on 2023-04-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_interests_anime_alter_interests_movies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(default="This is my bio", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pic"),
        ),
    ]
