# Generated by Django 4.2 on 2023-04-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_bio_alter_userprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(default="18", max_length=10),
            preserve_default=False,
        ),
    ]
